import fs from 'node:fs';import path from 'node:path';import {randomUUID} from 'node:crypto';import {execFileSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {baselineCommitment,sha256} from '../src/oos2rEvidence.js';import {readOos2tFreeze,auditOos2tBaselineBytes} from '../src/oos2tFreeze.js';import {OOS2T_PROTOCOL} from '../src/oos2tEvidence.js';import {validId} from '../../learning/src/cycleEvidenceManifest.js';
const fail=code=>{throw new Error(code);};
function timestampValues(record){const values=[record?.createdAt,record?.signalTimestamp,record?.settledAt,record?.clickTime,record?.execution?.plannedClickTime,record?.execution?.actualClickTime,record?.execution?.confirmedAt];const walk=(value,key='')=>{if(!value||typeof value!=='object')return;for(const [name,item] of Object.entries(value)){if(typeof item==='string'&&/(?:at|time|timestamp)$/i.test(name)&&Number.isFinite(Date.parse(item)))values.push(item);else if(item&&typeof item==='object')walk(item,name);}};walk(record?.outcomeMetadata);return values;}
function evidenceTimestamps(root){if(!path.isAbsolute(root)||!fs.existsSync(root)||fs.lstatSync(root).isSymbolicLink())fail('OOS2T_EVIDENCE_ROOT_INVALID');const values=[];const walk=dir=>{for(const item of fs.readdirSync(dir,{withFileTypes:true})){if(item.isSymbolicLink())fail('OOS2T_EVIDENCE_ROOT_INVALID');const p=path.join(dir,item.name);if(item.isDirectory())walk(p);else if(item.name.endsWith('.manifest.json')){let m;try{m=JSON.parse(fs.readFileSync(p,'utf8'));}catch{fail('OOS2T_EVIDENCE_MANIFEST_INVALID');}if(!Number.isFinite(Date.parse(m?.openedAt))||(m?.sealedAt!=null&&!Number.isFinite(Date.parse(m.sealedAt))))fail('OOS2T_EVIDENCE_TIMESTAMP_INVALID');values.push(m.openedAt,m.sealedAt);}}};walk(root);return values;}
export function assertOos2tTemporalBoundary(edgeCut,history,evidenceRoots=[]){const edge=Date.parse(edgeCut);if(!Number.isFinite(edge))fail('OOS2T_EXPLICIT_EDGE_CUT_REQUIRED');const values=history.flatMap(timestampValues);for(const root of evidenceRoots)values.push(...evidenceTimestamps(root));const times=values.map(Date.parse).filter(Number.isFinite);if(times.length&&edge<=Math.max(...times))fail('OOS2T_EDGE_CUT_NOT_AFTER_BASELINE');return {latestTimestamp:times.length?new Date(Math.max(...times)).toISOString():null};}
export function finalizeOos2tFreeze({historyFile,campaignId,edgeCut,freezeFile,evidenceRoots=[],write=false,confirmBackendStopped=false,now=()=>new Date().toISOString(),gitHead=()=>execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim()}={}){
  if(!path.isAbsolute(historyFile??'')||!path.isAbsolute(freezeFile??''))fail('OOS2T_ABSOLUTE_PATH_REQUIRED');if(!validId(campaignId)||campaignId===OOS2T_PROTOCOL)fail('OOS2T_CAMPAIGN_ID_REQUIRED');if(!Array.isArray(evidenceRoots)||evidenceRoots.some(root=>!path.isAbsolute(root)))fail('OOS2T_EVIDENCE_ROOT_INVALID');if(write&&!confirmBackendStopped)fail('OOS2T_BACKEND_STOP_CONFIRMATION_REQUIRED');if(fs.lstatSync(historyFile).isSymbolicLink())fail('OOS2T_HISTORY_SYMLINK');
  const historyBytes=fs.readFileSync(historyFile),history=JSON.parse(historyBytes.toString('utf8').replace(/^\uFEFF/,'')),commitment=baselineCommitment(history),historyFileSha256=sha256(historyBytes),temporal=assertOos2tTemporalBoundary(edgeCut,history,evidenceRoots),sourceHead=gitHead(),createdAt=now();
  if(!/^[a-f0-9]{40}$/i.test(sourceHead))fail('OOS2T_SOURCE_HEAD_INVALID');if(!Number.isFinite(Date.parse(createdAt))||Date.parse(createdAt)<Date.parse(edgeCut))fail('OOS2T_CREATED_AT_INVALID');
  const freeze={schemaVersion:'edge-gate-oos2t-freeze-v1',policy:'IMMUTABLE_AFTER_FREEZE',experiment:'WILL Edge Gate OOS-2T',protocolId:OOS2T_PROTOCOL,campaignId,edgeCut,createdAt:new Date(Date.parse(createdAt)).toISOString(),sourceHead,mode:'PAPER_READ_ONLY',metric:'MeanAbsMomentum',frozenThreshold:.599936,operator:'<=',baselineCount:commitment.baselineCount,baselineIdsSha256:commitment.baselineIdsSha256,historyFileSha256,checkpoint:{candidateCycles:50,selection:'first 50 exact campaign cycles ordered by openedAt then cycleId',replacement:'NONE'},bootstrap:{unit:'cycle',replications:10000,seed:20260915,rng:'xorshift32'},noRetuning:true,noEarlyStopping:true,noAutomaticLivePromotion:true,activationAuthorized:false};
  const bytes=Buffer.from(`${JSON.stringify(freeze,null,2)}\n`,'utf8'),freezeSha256=sha256(bytes),report={mode:write?'WRITE':'DRY_RUN',...commitment,historyFileSha256,freezeSha256,sourceHead,createdAt:freeze.createdAt,edgeCut,latestBaselineTimestamp:temporal.latestTimestamp,freeze};
  if(!write)return report;const sidecar=`${freezeFile}.sha256`;if(fs.existsSync(freezeFile)||fs.existsSync(sidecar))fail('OOS2T_FREEZE_ALREADY_EXISTS');fs.mkdirSync(path.dirname(freezeFile),{recursive:true});const tempFreeze=`${freezeFile}.${randomUUID()}.tmp`,tempHash=`${sidecar}.${randomUUID()}.tmp`;
  let published=false;try{fs.writeFileSync(tempFreeze,bytes,{flag:'wx'});fs.writeFileSync(tempHash,`${freezeSha256}\n`,{flag:'wx'});fs.renameSync(tempFreeze,freezeFile);fs.renameSync(tempHash,sidecar);published=true;const verified=readOos2tFreeze(freezeFile,sidecar);auditOos2tBaselineBytes(historyBytes,verified);if(verified.sourceHead!==gitHead()||verified.sourceHead!==sourceHead)fail('OOS2T_SOURCE_HEAD_CHANGED');if(verified.freezeSha256!==freezeSha256)fail('OOS2T_FREEZE_POSTWRITE_INVALID');}catch(error){if(published){for(const p of [freezeFile,sidecar])if(fs.existsSync(p))fs.unlinkSync(p);}throw error;}finally{for(const p of [tempFreeze,tempHash])if(fs.existsSync(p))fs.unlinkSync(p);}return report;
}
function arg(name){const i=process.argv.indexOf(name);return i<0?null:process.argv[i+1];}function args(name){const values=[];for(let i=0;i<process.argv.length;i++)if(process.argv[i]===name&&process.argv[i+1])values.push(process.argv[i+1]);return values;}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){try{const report=finalizeOos2tFreeze({historyFile:arg('--history'),campaignId:arg('--campaign-id'),edgeCut:arg('--edge-cut'),freezeFile:arg('--freeze'),evidenceRoots:args('--evidence-root'),write:process.argv.includes('--write'),confirmBackendStopped:process.argv.includes('--confirm-backend-stopped')});console.log(JSON.stringify(report,null,2));}catch(error){console.error(JSON.stringify({ok:false,error:String(error?.message||'OOS2T_FINALIZATION_FAILED')}));process.exitCode=1;}}
