import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {tmpdir} from 'node:os';
import {createCycleEvidenceJournal} from '../learning/src/cycleEvidenceJournal.js';import {createCycleEvidenceRuntime} from '../learning/src/cycleEvidenceRuntime.js';import {createAutonomousPaperMonitor,sanitizeObservationFailure} from '../learning/src/autonomousPaperMonitor.js';
import {replayEvidence} from '../backend/src/oos2rEvidence.js';import {verifyOos2tCycle,OOS2T_PROTOCOL} from '../backend/src/oos2tEvidence.js';import {evaluateOos2t} from '../backend/src/evaluateOos2t.js';import {inspectOos2tStatus} from '../backend/src/oos2tStatus.js';
const campaign='test-oos2t-campaign',opened='2026-09-20T00:00:00.001Z';
function temp(t){const root=fs.mkdtempSync(path.join(tmpdir(),'oos2t-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return root;}
function projections(dir){return fs.readdirSync(dir).filter(x=>x.endsWith('.manifest.json')).map(x=>JSON.parse(fs.readFileSync(path.join(dir,x),'utf8')));}
const cid=id=>id.startsWith('autonomous-paper-monitor-v1:')?id:`autonomous-paper-monitor-v1:${id}`;
function buildCycle(j,id,{terminal='SUCCESS',reasonCode=null,record=null}={}){id=cid(id);const m=j.openCycle({protocolId:OOS2T_PROTOCOL,campaignId:campaign,cycleId:id,openedAt:opened,history:[]});if(record){const row={...record,id:`r-${id}`,protocolId:OOS2T_PROTOCOL,campaignId:campaign,cycleId:id,writerGeneration:m.writerGeneration,metadata:{...record.metadata,context:{monitorCycleId:id}}};j.beginWriter({...m,writerId:'w'});j.beginRecordCreation({...m,writerId:'w',operationId:'op',record:row});j.commitRecordCreation({...m,operationId:'op'});j.endWriter({...m,writerId:'w'});}j.commitObservationTerminal({...m,outcome:terminal,reasonCode});j.sealCycle({...m,sealedAt:'2026-09-20T00:00:00.002Z'});return m;}
function evidence(dir){return {walBytes:fs.readFileSync(path.join(dir,'journal.jsonl')),manifests:projections(dir)};}
const freeze={protocolId:OOS2T_PROTOCOL,campaignId:campaign,edgeCut:'2026-09-20T00:00:00.000Z',frozenThreshold:.599936,operator:'<=',metric:'MeanAbsMomentum'};

test('SUCCESS terminal seals a zero-record cycle and replay is deterministic',t=>{const d=temp(t),j=createCycleEvidenceJournal({directory:d,observationTerminalRequired:true});buildCycle(j,'c');const [e]=replayEvidence(...Object.values(evidence(d)));assert.equal(e.observationTerminal.outcome,'SUCCESS');assert.equal(verifyOos2tCycle(e,[]).complete,true);assert.deepEqual(replayEvidence(...Object.values(evidence(d))),[e]);});
test('OPERATIONAL_FAILURE is complete, record-free and reason-counted',t=>{const d=temp(t),j=createCycleEvidenceJournal({directory:d,observationTerminalRequired:true});buildCycle(j,'c',{terminal:'OPERATIONAL_FAILURE',reasonCode:'REQUEST_TIMEOUT'});const [e]=replayEvidence(...Object.values(evidence(d))),v=verifyOos2tCycle(e,[]),s=inspectOos2tStatus({...evidence(d),history:[],campaignId:campaign,edgeCut:freeze.edgeCut});assert.equal(v.complete,true);assert.equal(v.records.length,0);assert.deepEqual(s.first50.observationFailureReasonCounts,{REQUEST_TIMEOUT:1});});
test('terminal is exactly once and blocks writers, records and seal-before-terminal',t=>{const d=temp(t),j=createCycleEvidenceJournal({directory:d,observationTerminalRequired:true}),m=j.openCycle({protocolId:OOS2T_PROTOCOL,campaignId:campaign,cycleId:cid('c'),openedAt:opened,history:[]});assert.throws(()=>j.sealCycle({...m,sealedAt:opened}),/TERMINAL_REQUIRED/);j.commitObservationTerminal({...m,outcome:'SUCCESS'});assert.throws(()=>j.commitObservationTerminal({...m,outcome:'SUCCESS'}),/TERMINAL_EXISTS|STORAGE/);assert.throws(()=>j.beginWriter({...m,writerId:'w'}),/WRITER_BLOCKED/);});
test('reason validation rejects unsafe or unbounded provenance',t=>{for(const [i,code] of ['token=abc','A'.repeat(65),'line\nbearer x',''].entries()){const d=path.join(temp(t),String(i)),j=createCycleEvidenceJournal({directory:d,observationTerminalRequired:true}),m=j.openCycle({protocolId:OOS2T_PROTOCOL,campaignId:campaign,cycleId:cid(`c-${i}`),openedAt:opened,history:[]});assert.throws(()=>j.commitObservationTerminal({...m,outcome:'OPERATIONAL_FAILURE',reasonCode:code}));}});
test('sanitizer maps timeout/network and never returns secret text',()=>{assert.equal(sanitizeObservationFailure(new DOMException('x','TimeoutError')),'REQUEST_TIMEOUT');assert.equal(sanitizeObservationFailure(Object.assign(Error('https://u:p@x/?api_key=secret\nstack'),{code:'ECONNRESET'})),'NETWORK_FAILURE');for(const secret of ['secret','bearer','password','api_key'])assert.equal(sanitizeObservationFailure(Error(secret)).includes(secret.toUpperCase()),false);assert.equal(sanitizeObservationFailure('PROVIDER_API_KEY_SECRET'),'CYCLE_ERROR');});
test('monitor ok:false and thrown timeout seal as operational failures without fake records',async t=>{for(const [name,run,code] of [['return',async()=>({ok:false,status:'PROVIDER_UNAVAILABLE'}),'PROVIDER_UNAVAILABLE'],['throw',async()=>{throw new DOMException('Bearer secret','TimeoutError');},'REQUEST_TIMEOUT']]){const root=path.join(temp(t),name),state=path.join(root,'state.json'),rows=[],store={list:()=>rows,prepareDecisionRecord(){},insertPreparedRecord(){}};const runtime=createCycleEvidenceRuntime({directory:path.join(root,'e'),protocolId:OOS2T_PROTOCOL,campaignId:campaign,historyStore:store,observationTerminalRequired:true,now:()=>opened});const monitor=createAutonomousPaperMonitor({enabled:true,filePath:state,runCycle:run,cycleEvidence:runtime,now:()=>1});await monitor.runOnce();const wal=fs.readFileSync(path.join(root,'e','journal.jsonl')),[e]=replayEvidence(wal,projections(path.join(root,'e')));assert.deepEqual(e.observationTerminal,{outcome:'OPERATIONAL_FAILURE',reasonCode:code,sequence:2});assert.deepEqual(e.manifest.recordIds,[]);assert.equal(e.manifest.state,'SEALED');assert.equal(wal.toString().includes('secret'),false);}});
test('monitor success commits SUCCESS before seal',async t=>{const root=temp(t),rows=[],runtime=createCycleEvidenceRuntime({directory:path.join(root,'e'),protocolId:OOS2T_PROTOCOL,campaignId:campaign,historyStore:{list:()=>rows,prepareDecisionRecord(){},insertPreparedRecord(){}},observationTerminalRequired:true,now:()=>opened}),monitor=createAutonomousPaperMonitor({enabled:true,filePath:path.join(root,'s.json'),runCycle:async()=>({ok:true}),cycleEvidence:runtime,now:()=>1});assert.equal((await monitor.runOnce()).status,'COMPLETED');assert.equal(replayEvidence(fs.readFileSync(path.join(root,'e','journal.jsonl')),projections(path.join(root,'e')))[0].observationTerminal.outcome,'SUCCESS');});
test('storage failure pauses and is never recorded as operational failure',async()=>{let terminal=false;const runtime={health:()=>({paused:false,observationTerminalRequired:true}),recover:()=>({sealedCycleIds:[]}),openMonitorCycle(){throw Error('WAL_WRITE_UNCERTAIN');},commitObservationTerminal(){terminal=true;},pause(){}};const monitor=createAutonomousPaperMonitor({enabled:true,filePath:path.join(tmpdir(),`missing-${Date.now()}`,'s.json'),runCycle:async()=>({ok:true}),cycleEvidence:runtime,now:()=>1});assert.equal((await monitor.runOnce()).status,'PAUSED');assert.equal(terminal,false);});
test('SKIPPED and DATA_INVALID remain distinct from observation failure',t=>{const d=temp(t),j=createCycleEvidenceJournal({directory:d,observationTerminalRequired:true});const skipped={status:'SKIPPED',direction:'WAIT',execution:null,outcome:null,settledAt:null,clickTime:null,metadata:{featureSnapshot:{momentum:.2}}};buildCycle(j,'skip',{record:skipped});let [e]=replayEvidence(...Object.values(evidence(d))),v=verifyOos2tCycle(e,[e.creations[0]]);assert.equal(v.noTradeRecords,1);assert.equal(v.observationOutcome,'SUCCESS');const d2=temp(t),j2=createCycleEvidenceJournal({directory:d2,observationTerminalRequired:true}),initial={status:'OPEN',direction:'BUY',execution:null,outcome:null,settledAt:null,clickTime:null,metadata:{featureSnapshot:{momentum:.2}}};buildCycle(j2,'invalid-data',{record:initial});[e]=replayEvidence(...Object.values(evidence(d2)));const current={...e.creations[0],status:'CLOSED',outcome:'DATA_INVALID',settledAt:'2026-09-20T00:00:00.002Z'};v=verifyOos2tCycle(e,[current]);assert.equal(v.complete,true);assert.equal(v.dataInvalidRecords,1);assert.equal(v.observationFailureReason,null);});
test('corrupt projection, WAL truncation and membership mismatch fail closed',t=>{const d=temp(t),j=createCycleEvidenceJournal({directory:d,observationTerminalRequired:true});buildCycle(j,'c');const ev=evidence(d);assert.equal(verifyOos2tCycle({...replayEvidence(ev.walBytes,ev.manifests)[0],projectionValid:false},[]).valid,false);assert.throws(()=>replayEvidence(Buffer.from(ev.walBytes.toString().slice(0,-1)),ev.manifests));});
test('historical WAL without observation terminals retains old replay shape',t=>{const d=temp(t),j=createCycleEvidenceJournal({directory:d});const m=j.openCycle({protocolId:'old-protocol',campaignId:'old-campaign',cycleId:cid('old'),openedAt:opened,history:[]});j.sealCycle({...m,sealedAt:opened});const [e]=replayEvidence(...Object.values(evidence(d)));assert.equal('observationTerminal' in e,false);assert.equal(e.manifest.state,'SEALED');});

function firstN(t,n,{invalidate=false,failures=0}={}){const d=temp(t),j=createCycleEvidenceJournal({directory:d,observationTerminalRequired:true});for(let i=0;i<n;i++){const id=cid(`c-${String(i).padStart(2,'0')}`),m=j.openCycle({protocolId:OOS2T_PROTOCOL,campaignId:campaign,cycleId:id,openedAt:new Date(Date.parse(opened)+i).toISOString(),history:[]});if(invalidate&&i===0){j.invalidateCycle({cycleId:id});continue;}j.commitObservationTerminal({...m,outcome:i<failures?'OPERATIONAL_FAILURE':'SUCCESS',reasonCode:i<failures?'PROVIDER_FAILURE':null});j.sealCycle({...m,sealedAt:new Date(Date.parse(opened)+100+i).toISOString()});}return {d,...evidence(d)};}
test('evaluator blocks at 49 and emits no partial performance',t=>{const x=firstN(t,49),r=evaluateOos2t({...x,history:[],freeze,freezeVerified:true,baselineIntegrity:'PASS'});assert.equal(r.formalAnalysisAllowed,false);assert.equal('analysis' in r,false);});
test('valid complete first 50 permits formal analysis and preserves failure slots',t=>{const x=firstN(t,51,{failures:2}),r=evaluateOos2t({...x,history:[],freeze,freezeVerified:true,baselineIntegrity:'PASS'});assert.equal(r.formalAnalysisAllowed,true);assert.equal(r.completedCandidateCycles,50);assert.equal(r.observationFailureCycles,2);assert.deepEqual(r.selectedCycleIds.slice(0,2),[cid('c-00'),cid('c-01')]);assert.equal(r.metricValidCycles,0);assert.equal(r.metricInvalidCycles,50);assert.equal(r.analysis.performanceRecords,0);});
test('true INVALID among first 50 blocks formal analysis',t=>{const x=firstN(t,50,{invalidate:true}),r=evaluateOos2t({...x,history:[],freeze,freezeVerified:true,baselineIntegrity:'PASS'});assert.equal(r.formalAnalysisAllowed,false);assert.equal(r.evidenceIntegrity,'FAIL');});
test('failure reason aggregation is deterministic',t=>{const x=firstN(t,50,{failures:3}),a=evaluateOos2t({...x,history:[],freeze,freezeVerified:true,baselineIntegrity:'PASS'}),b=evaluateOos2t({...x,history:[],freeze,freezeVerified:true,baselineIntegrity:'PASS'});assert.deepEqual(a.observationFailureReasonCounts,b.observationFailureReasonCounts);assert.deepEqual(a.observationFailureReasonCounts,{PROVIDER_FAILURE:3});});
test('unverified future freeze can never unlock formal analysis',()=>{assert.equal(evaluateOos2t({freeze,baselineIntegrity:'PASS'}).formalAnalysisAllowed,false);});
