import test from 'node:test';import assert from 'node:assert/strict';
import { newManifest,canonicalDigest } from '../learning/src/cycleEvidenceManifest.js';
import { classifyOos2sRecord,verifyOos2sCycle,OOS2S_PROTOCOL,OOS2S_CAMPAIGN } from '../backend/src/oos2sEvidence.js';

const openedAt='2026-09-19T10:00:00.000Z';
function fixture(direction='WAIT'){
  const manifest=newManifest({protocolId:OOS2S_PROTOCOL,campaignId:OOS2S_CAMPAIGN,cycleId:'autonomous-paper-monitor-v1:test',writerGeneration:1,openedAt});manifest.recordIds=['r'];manifest.expectedRecordCount=1;manifest.inventoryRevision=1;
  const base={id:'r',protocolId:OOS2S_PROTOCOL,campaignId:OOS2S_CAMPAIGN,cycleId:manifest.cycleId,writerGeneration:1,status:'SKIPPED',direction,execution:null,outcome:null,settledAt:null,clickTime:null,metadata:{context:{monitorCycleId:manifest.cycleId}}};return {manifest,base};
}
for(const direction of ['WAIT','BUY','SELL'])test(`WAL-born SKIPPED ${direction} is terminal no-trade without direction gate`,()=>{const {manifest,base}=fixture(direction);assert.deepEqual(classifyOos2sRecord(base,structuredClone(base),manifest),{terminal:true,class:'NO_TRADE_TERMINAL'});});
test('SKIPPED with execution, outcome, or post-creation mutation is non-terminal',()=>{for(const patch of [{execution:{status:'PAPER_CONFIRMED'}},{outcome:'WIN'},{asset:'MUTATED'}]){const {manifest,base}=fixture();const current={...base,...patch};assert.equal(classifyOos2sRecord(current,base,manifest).terminal,false);}});
test('OPEN BUY/SELL remain pending',()=>{for(const direction of ['BUY','SELL']){const {manifest,base}=fixture(direction);const open={...base,status:'OPEN'};assert.equal(classifyOos2sRecord(open,open,manifest).terminal,false);}});
test('official trade terminals require executable creation and exact provenance; DATA_INVALID remains separate',()=>{const {manifest,base}=fixture('BUY'),initial={...base,status:'OPEN'};const trade={...initial,status:'CLOSED',outcome:'WIN',settledAt:'2026-09-19T10:01:00.000Z',execution:{status:'PAPER_CONFIRMED'},outcomeMetadata:{settlementVersion:'paper-outcome-settlement-v2',source:'paper-live-temporal-reference-v1'}};assert.equal(classifyOos2sRecord(trade,initial,manifest).class,'TRADE_TERMINAL');assert.equal(classifyOos2sRecord({...trade,execution:null},initial,manifest).terminal,false);assert.equal(classifyOos2sRecord({...trade,outcome:'DATA_INVALID',execution:null,outcomeMetadata:null},initial,manifest).class,'DATA_INVALID_TERMINAL');});
test('WAL-born SKIPPED cannot be rewritten into any trade or DATA_INVALID terminal',()=>{for(const outcome of ['WIN','LOSS','TIE','DATA_INVALID']){const {manifest,base}=fixture('BUY'),current={...base,status:'CLOSED',outcome,settledAt:'2026-09-19T10:01:00.000Z',execution:{status:'PAPER_CONFIRMED'},outcomeMetadata:{settlementVersion:'paper-outcome-settlement-v2',source:'paper-live-temporal-reference-v1'}};assert.equal(classifyOos2sRecord(current,base,manifest).terminal,false);}});
test('three official trades plus one unchanged SKIPPED complete a SEALED inventory',()=>{const {manifest,base}=fixture();manifest.recordIds=['r','w','l','t'];manifest.expectedRecordCount=4;manifest.inventoryRevision=4;manifest.canonicalDigest=canonicalDigest(manifest);manifest.state='SEALED';manifest.sealedAt='2026-09-19T10:02:00.000Z';manifest.sealSequence=9;const trade=(id,outcome)=>({...base,id,direction:'BUY',status:'CLOSED',outcome,settledAt:'2026-09-19T10:01:00.000Z',execution:{status:'PAPER_CONFIRMED'},outcomeMetadata:{settlementVersion:'paper-outcome-settlement-v2',source:'paper-live-temporal-reference-v1'}});const history=[base,trade('w','WIN'),trade('l','LOSS'),trade('t','TIE')],creations=history.map(x=>x.id==='r'?structuredClone(x):{...x,status:'OPEN',outcome:null,settledAt:null,execution:null,outcomeMetadata:null});const r=verifyOos2sCycle({manifest,projectionValid:true,creations},history);assert.equal(r.complete,true);assert.equal(r.noTradeRecords,1);assert.equal(r.tradeTerminalRecords,3);});
test('post-intent momentum mutation invalidates creation consistency',()=>{const {manifest,base}=fixture('BUY'),initial={...base,status:'OPEN',metadata:{...base.metadata,featureSnapshot:{momentum:.2}}},current={...initial,status:'CLOSED',outcome:'WIN',settledAt:'2026-09-19T10:01:00.000Z',execution:{status:'PAPER_CONFIRMED'},outcomeMetadata:{settlementVersion:'paper-outcome-settlement-v2',source:'paper-live-temporal-reference-v1'},metadata:{...initial.metadata,featureSnapshot:{momentum:.8}}};assert.equal(classifyOos2sRecord(current,initial,manifest).reason,'CREATION_FIELDS_MUTATED');});
