import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {tmpdir} from 'node:os';
import { baselineCommitment,sha256 } from '../backend/src/oos2rEvidence.js';
import { inspectOos2sActivation,prepareOos2sEnvironment,createPreparedOos2sRuntime,OOS2S_START_AUTHORIZATION } from '../backend/src/oos2sActivation.js';
import { OOS2S_PROTOCOL,OOS2S_CAMPAIGN } from '../backend/src/oos2sEvidence.js';
import { inspectOos2sStatus } from '../backend/src/oos2sStatus.js';
import { evaluateOos2s } from '../backend/src/evaluateOos2s.js';
import { createCycleEvidenceJournal } from '../learning/src/cycleEvidenceJournal.js';
import { finalizeOos2sFreeze,validateOos2rSnapshot,assertOos2rJournalHash } from '../backend/scripts/finalizeOos2sFreeze.mjs';
import { readOos2sFreeze } from '../backend/src/oos2sFreeze.js';

function temp(t){const root=fs.mkdtempSync(path.join(tmpdir(),'will-oos2s-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return root;}
function activationFixture(t){const root=temp(t),historyFile=path.join(root,'history.json'),rows=[{id:'a'},{id:'b'}];fs.writeFileSync(historyFile,JSON.stringify(rows));const freeze={schemaVersion:'edge-gate-oos2s-freeze-v1',policy:'IMMUTABLE_AFTER_FREEZE',protocolId:OOS2S_PROTOCOL,campaignId:OOS2S_CAMPAIGN,frozenThreshold:.599936,operator:'<=',metric:'MeanAbsMomentum',activationAuthorized:false,edgeCut:'2026-09-19T00:00:00.000Z',...baselineCommitment(rows),historyFileSha256:sha256(fs.readFileSync(historyFile))};return {root,historyFile,rows,freeze,readFreeze:()=>freeze,options:{historyFile,evidenceDirectory:path.join(root,'oos2s-evidence-20260919-v1'),scanRoots:[root],readFreeze:()=>freeze,now:()=>Date.parse(freeze.edgeCut)+1}};}
test('OOS2S preflight is read-only and validates full-file hash',t=>{const s=activationFixture(t),before=fs.readFileSync(s.historyFile);assert.equal(inspectOos2sActivation(s.options).ready,true);assert.equal(fs.existsSync(s.options.evidenceDirectory),false);assert.deepEqual(fs.readFileSync(s.historyFile),before);fs.writeFileSync(s.historyFile,`${before.toString()} `);assert.throws(()=>inspectOos2sActivation(s.options),/BASELINE_CONTINUITY/);});
test('partial OOS2S activation signals fail closed while unrelated legacy remains inert',()=>{for(const env of [{WILL_OOS2S_START_AUTHORIZATION:'bad'},{WILL_CYCLE_EVIDENCE_PROTOCOL_ID:OOS2S_PROTOCOL},{WILL_CYCLE_EVIDENCE_CAMPAIGN_ID:OOS2S_CAMPAIGN},{WILL_CYCLE_EVIDENCE_DIRECTORY:'C:/x/oos2s-evidence-20260919-v1'}])assert.throws(()=>prepareOos2sEnvironment(env),/EXACT/);assert.equal(prepareOos2sEnvironment({WILL_CYCLE_EVIDENCE_PROTOCOL_ID:'legacy'}),null);});
test('history mutation between preflight and first OPEN pauses fail-closed',t=>{const s=activationFixture(t),store={list:()=>structuredClone(s.rows),prepareDecisionRecord(){},insertPreparedRecord(){}};const runtime=createPreparedOos2sRuntime({prepared:{options:s.options},historyStore:store,now:s.options.now,readFreeze:s.readFreeze});runtime.recover();s.rows.push({id:'late'});fs.writeFileSync(s.historyFile,JSON.stringify(s.rows));assert.throws(()=>runtime.openMonitorCycle('autonomous-paper-monitor-v1:x'),/BASELINE_CHANGED/);assert.equal(runtime.health().paused,true);});
test('status sanitizes freeze failure, truncated WAL and corrupt projection',t=>{const root=temp(t),freeze={protocolId:OOS2S_PROTOCOL,campaignId:OOS2S_CAMPAIGN,edgeCut:'2026-09-19T00:00:00.000Z'};assert.equal(inspectOos2sStatus({evidenceDirectory:path.join(root,'none'),readFreeze:()=>{throw Error(`secret ${root}`);}}).error,'OOS2S_FREEZE_INVALID');const evidence=path.join(root,'e');fs.mkdirSync(evidence);fs.writeFileSync(path.join(evidence,'journal.jsonl'),'{}');let r=inspectOos2sStatus({evidenceDirectory:evidence,readFreeze:()=>freeze});assert.equal(r.error,'OOS2S_EVIDENCE_INVALID');assert.equal(JSON.stringify(r).includes(root),false);fs.rmSync(evidence,{recursive:true});const j=createCycleEvidenceJournal({directory:evidence});j.openCycle({protocolId:OOS2S_PROTOCOL,campaignId:OOS2S_CAMPAIGN,cycleId:'autonomous-paper-monitor-v1:x',openedAt:'2026-09-19T00:00:00.001Z',history:[]});const projection=fs.readdirSync(evidence).find(x=>x.endsWith('.manifest.json'));fs.writeFileSync(path.join(evidence,projection),'{}');r=inspectOos2sStatus({evidenceDirectory:evidence,readFreeze:()=>freeze});assert.equal(r.error,'OOS2S_PROJECTION_INVALID');});
test('status fails closed on identity mismatch and openedAt at cutoff',t=>{const root=temp(t),freeze={protocolId:OOS2S_PROTOCOL,campaignId:OOS2S_CAMPAIGN,edgeCut:'2026-09-19T00:00:00.000Z'};for(const [name,protocolId,campaignId,openedAt,error] of [['identity','wrong',OOS2S_CAMPAIGN,'2026-09-19T00:00:00.001Z','OOS2S_IDENTITY_MISMATCH'],['time',OOS2S_PROTOCOL,OOS2S_CAMPAIGN,freeze.edgeCut,'OOS2S_TEMPORAL_MEMBERSHIP_INVALID']]){const directory=path.join(root,name),j=createCycleEvidenceJournal({directory});j.openCycle({protocolId,campaignId,cycleId:`autonomous-paper-monitor-v1:${name}`,openedAt,history:[]});assert.equal(inspectOos2sStatus({evidenceDirectory:directory,history:[],readFreeze:()=>freeze}).error,error);}});
test('evaluator never emits partial performance and retains preformal slot count',()=>{const freeze={protocolId:OOS2S_PROTOCOL,campaignId:OOS2S_CAMPAIGN,edgeCut:'2026-09-19T00:00:00.000Z',frozenThreshold:.599936,operator:'<=',baselineCount:0,baselineIdsSha256:baselineCommitment([]).baselineIdsSha256,historyFileSha256:'h'};const report=evaluateOos2s({history:[],walBytes:Buffer.alloc(0),manifests:[],freeze,baselineAudit:{baselineCount:0,baselineIdsSha256:freeze.baselineIdsSha256,historyFileSha256:'h'}});assert.equal(report.formalAnalysisAllowed,false);assert.equal('analysis' in report,false);assert.equal(report.candidateCyclesObserved,0);});
test('freeze reader requires sidecar and exact bytes',t=>{const root=temp(t),file=path.join(root,'freeze.json');fs.writeFileSync(file,'{}\n');fs.writeFileSync(`${file}.sha256`,`${sha256(fs.readFileSync(file))}\n`);assert.throws(()=>readOos2sFreeze(file),/FREEZE_INVALID/);fs.writeFileSync(`${file}.sha256`,'0'.repeat(64));assert.throws(()=>readOos2sFreeze(file),/FREEZE_INVALID/);});
test('finalizer refuses wrong real-history bytes and performs zero writes in dry-run',t=>{const root=temp(t),history=path.join(root,'history.json'),evidence=path.join(root,'e'),freeze=path.join(root,'freeze.json');fs.writeFileSync(history,'[]');fs.mkdirSync(evidence);assert.throws(()=>finalizeOos2sFreeze({historyFile:history,oos2rEvidenceDirectory:evidence,edgeCut:'2026-09-19T12:00:00.000Z',freezeFile:freeze}),/HISTORY_SHA/);assert.equal(fs.existsSync(freeze),false);assert.equal(fs.existsSync(`${freeze}.sha256`),false);});
test('finalizer snapshot validator rejects non-23 cycle evidence',()=>{assert.throws(()=>validateOos2rSnapshot([]),/SNAPSHOT_MISMATCH/);});
test('finalizer rejects wrong OOS2R journal SHA independently',()=>{assert.throws(()=>assertOos2rJournalHash(Buffer.from('wrong')),/JOURNAL_SHA_MISMATCH/);});
test('activation literal is frozen',()=>{assert.equal(OOS2S_START_AUTHORIZATION,'START_APPROVED_OOS2S_FIRST_COLLECTION_V1');});
test('server gates OOS2S before secrets and scopes settlement by exact campaign',()=>{const source=fs.readFileSync(new URL('../backend/src/server.js',import.meta.url),'utf8');assert.ok(source.indexOf('const oos2sPrepared = prepareOos2sEnvironment()')<source.indexOf('const runtimeSecrets = await hydrateRuntimeSecrets()'));assert.match(source,/scope:oos2sPrepared\?\{protocolId:'will-edge-gate-oos2s-v1',campaignId:'will-edge-gate-oos2s-20260919-v1'\}:null/);});
