import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {tmpdir} from 'node:os';
import {finalizeOos2tFreeze} from '../backend/scripts/finalizeOos2tFreeze.mjs';import {baselineCommitment,sha256} from '../backend/src/oos2rEvidence.js';import {readOos2tFreeze,auditOos2tBaselineBytes} from '../backend/src/oos2tFreeze.js';
const head='b'.repeat(40),campaign='fixture-oos2t-finalizer',edgeCut='2026-09-22T00:00:00.000Z',createdAt='2026-09-22T00:00:01.000Z';
function fixture(t){const root=fs.mkdtempSync(path.join(tmpdir(),'oos2t-finalizer-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const historyFile=path.join(root,'history.json'),freezeFile=path.join(root,'freeze.json'),history=[{id:'b',createdAt:'2026-09-21T20:00:00.000Z',signalTimestamp:'2026-09-21T20:01:00.000Z',execution:{plannedClickTime:'2026-09-21T20:02:00.000Z',actualClickTime:'2026-09-21T20:03:00.000Z',confirmedAt:'2026-09-21T20:04:00.000Z'},outcomeMetadata:{referenceTimestamp:'2026-09-21T20:05:00.000Z'}},{id:'a',settledAt:'2026-09-21T21:00:00.000Z'}];fs.writeFileSync(historyFile,JSON.stringify(history));return {root,historyFile,freezeFile,history,bytes:fs.readFileSync(historyFile),options:{historyFile,freezeFile,campaignId:campaign,edgeCut,now:()=>createdAt,gitHead:()=>head}};}
test('dry-run derives exact commitments and creates zero files',t=>{const s=fixture(t),before=fs.readdirSync(s.root),r=finalizeOos2tFreeze(s.options);assert.equal(r.mode,'DRY_RUN');assert.deepEqual({baselineCount:r.baselineCount,baselineIdsSha256:r.baselineIdsSha256},baselineCommitment(s.history));assert.equal(r.historyFileSha256,sha256(s.bytes));assert.equal(r.sourceHead,head);assert.deepEqual(fs.readdirSync(s.root),before);});
test('edgeCut must be strictly after every baseline timestamp',t=>{const s=fixture(t);for(const cut of ['2026-09-21T20:05:00.000Z','2026-09-21T20:59:59.999Z','2026-09-21T21:00:00.000Z'])assert.throws(()=>finalizeOos2tFreeze({...s.options,edgeCut:cut}),/NOT_AFTER_BASELINE/);});
test('existing freeze or sidecar is never overwritten',t=>{const s=fixture(t);fs.writeFileSync(s.freezeFile,'existing');assert.throws(()=>finalizeOos2tFreeze({...s.options,write:true,confirmBackendStopped:true}),/ALREADY_EXISTS/);assert.equal(fs.readFileSync(s.freezeFile,'utf8'),'existing');});
test('write creates verified freeze and sidecar then exact baseline audit passes',t=>{const s=fixture(t),r=finalizeOos2tFreeze({...s.options,write:true,confirmBackendStopped:true});assert.equal(r.mode,'WRITE');assert.equal(fs.readFileSync(`${s.freezeFile}.sha256`,'utf8').trim(),r.freezeSha256);const freeze=readOos2tFreeze(s.freezeFile,`${s.freezeFile}.sha256`);assert.equal(freeze.sourceHead,head);assert.equal(freeze.protocolId,'will-edge-gate-oos2t-v1');assert.equal(freeze.campaignId,campaign);assert.equal(auditOos2tBaselineBytes(s.bytes,freeze).status,'PASS');assert.throws(()=>auditOos2tBaselineBytes(Buffer.from(`${s.bytes} `),freeze),/AUDIT_FAILED/);});
test('write requires explicit stopped confirmation and current sourceHead stays pinned',t=>{const s=fixture(t);assert.throws(()=>finalizeOos2tFreeze({...s.options,write:true}),/STOP_CONFIRMATION/);let calls=0;assert.throws(()=>finalizeOos2tFreeze({...s.options,write:true,confirmBackendStopped:true,gitHead:()=>++calls===1?head:'c'.repeat(40)}),/SOURCE_HEAD_CHANGED/);});
