import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { tmpdir } from 'node:os';
import historyRouter from '../backend/src/routes/history.js';
import { settleDuePaperCampaignOutcomes } from '../backend/src/paperOutcomeSettlement.js';
import { createHistoryStore } from '../learning/src/historyStore.js';
import { createCycleEvidenceRuntime } from '../learning/src/cycleEvidenceRuntime.js';
import { createAutonomousPaperMonitor } from '../learning/src/autonomousPaperMonitor.js';
import { OOS2U_PROTOCOL, OOS2U_STRUCTURAL_CONTRACT, validateOos2uDraft } from '../backend/src/oos2uProtocol.js';

const campaign='fixture-oos2u-campaign', cycleId='autonomous-paper-monitor-v1:1';
const membership={protocolId:OOS2U_PROTOCOL,campaignId:campaign,cycleId,writerGeneration:1};
const root=t=>{const value=fs.mkdtempSync(path.join(tmpdir(),'oos2u-isolation-'));t.after(()=>fs.rmSync(value,{recursive:true,force:true}));return value;};
function protectedStore(){const store=createHistoryStore({now:()=> '2026-09-22T00:00:10.000Z',id:()=> 'protected-record'});const record=store.prepareDecisionRecord({decision:{direction:'BUY',releaseEligible:true,clickTime:'2026-09-22T00:00:00.000Z'},data:{asset:'EUR/USD',timeframe:'1min',price:1.1},context:{monitorCycleId:cycleId,expirySeconds:60}},membership);store.insertPreparedRecord(record);return store;}
function route(method,routePath){return historyRouter.stack.find(layer=>layer.route?.path===routePath&&layer.route.methods[method]).route.stack.at(-1).handle;}
function response(){return {code:200,body:null,status(value){this.code=value;return this;},json(value){this.body=value;return this;}};}

test('storage blocks manual execution and outcome but dedicated PAPER authority remains valid',()=>{const store=protectedStore();assert.throws(()=>store.confirmExecution('protected-record',{actualClickTime:'2026-09-22T00:00:01.000Z'}),/PROTECTED_PROSPECTIVE_MUTATION_FORBIDDEN/);assert.throws(()=>store.settle('protected-record','WIN',{authority:'paper',paperOnly:true}),/PROTECTED_PROSPECTIVE_MUTATION_FORBIDDEN/);const paper=store.confirmPaperExecution('protected-record',{referenceTimestamp:'2026-09-22T00:00:01.000Z',referencePrice:1.1,source:'fixture'});assert.equal(paper.execution.status,'PAPER_CONFIRMED');const closed=store.settlePaperOutcome('protected-record','WIN',{settlementVersion:'paper-outcome-settlement-v2',source:'paper-live-temporal-reference-v1',paperOnly:true,automatedBrokerExecution:false});assert.equal(closed.outcome,'WIN');assert.equal(closed.execution.status,'PAPER_CONFIRMED');assert.equal(closed.outcomeMetadata.automatedBrokerExecution,false);});

test('manual API rejects protected execution/outcome and history projection hides it',async()=>{for(const [routePath,body] of [['/history/:id/executed',{actualClickTime:'2026-09-22T00:00:01.000Z'}],['/history/:id/outcome',{outcome:'WIN'}]]){const store=protectedStore(),res=response();await route('post',routePath)({params:{id:'protected-record'},body,app:{locals:{historyStore:store}}},res);assert.equal(res.code,400);assert.equal(res.body.error,'PROTECTED_PROSPECTIVE_MUTATION_FORBIDDEN');assert.equal(store.list()[0].status,'OPEN');}const store=protectedStore(),res=response();await route('get','/history')({query:{},app:{locals:{historyStore:store}}},res);assert.equal(res.body.total,0);assert.deepEqual(res.body.records,[]);});

test('generic resolver never selects a protected record',async()=>{const store=protectedStore(),res=response();await route('post','/history/resolve')({body:{limit:3},app:{locals:{historyStore:store}}},res);assert.equal(res.code,200);assert.deepEqual(res.body,{ok:true,resolved:[],pending:[]});assert.equal(store.list()[0].status,'OPEN');});

test('official PAPER settlement uses internal outcome authority and exact provenance',()=>{const store=protectedStore(),feed={referenceAtOrAfter:(_asset,target)=>Number(target)===Date.parse('2026-09-22T00:00:00.000Z')?{provider:'fixture',price:1.1,timestamp:'2026-09-22T00:00:01.000Z',lagMs:1000,valid:true,status:'OK'}:{provider:'fixture',price:1.2,timestamp:'2026-09-22T00:01:02.000Z',lagMs:1000,valid:true,status:'OK'}};const result=settleDuePaperCampaignOutcomes({historyStore:store,biquoteForexFeed:feed,scope:{protocolId:OOS2U_PROTOCOL,campaignId:campaign},now:Date.parse('2026-09-22T00:01:10.000Z')});assert.equal(result.settled,1);const record=store.list()[0];assert.equal(record.execution.status,'PAPER_CONFIRMED');assert.equal(record.outcomeMetadata.settlementVersion,'paper-outcome-settlement-v2');assert.equal(record.outcomeMetadata.source,'paper-live-temporal-reference-v1');assert.equal(record.outcomeMetadata.automatedBrokerExecution,false);});

function runtime(t,directory,store=createHistoryStore()){return createCycleEvidenceRuntime({directory,protocolId:OOS2U_PROTOCOL,campaignId:campaign,historyStore:store,observationTerminalRequired:true,maxCandidateCycles:50,now:()=> '2026-09-22T00:00:00.000Z'});}
function fill(runtime,count){for(let i=0;i<count;i++){const id=`autonomous-paper-monitor-v1:${i}`;runtime.openMonitorCycle(id);runtime.commitObservationTerminal(id,{outcome:i===10?'OPERATIONAL_FAILURE':'SUCCESS',reasonCode:i===10?'CYCLE_ERROR':null});runtime.sealMonitorCycle(id);}}

test('hard stop admits exactly slots 1..50 and operational failure is not replaced',t=>{const r=runtime(t,root(t));r.recover();fill(r,50);assert.deepEqual(r.health(),{ready:true,paused:false,observationTerminalRequired:true,candidateCyclesObserved:50,candidateCycleLimit:50,collectionClosed:true,newCandidateAdmissionAllowed:false});assert.throws(()=>r.openMonitorCycle('autonomous-paper-monitor-v1:50'),/EVIDENCE_CANDIDATE_LIMIT_REACHED/);assert.equal(r.health().paused,false);});

test('restart at 50 stays closed and scheduler performs no observation',async t=>{const directory=root(t),store=createHistoryStore(),first=runtime(t,directory,store);first.recover();fill(first,50);const next=runtime(t,directory,store),state=path.join(root(t),'monitor.json');fs.writeFileSync(state,JSON.stringify({monitorVersion:'autonomous-paper-monitor-v1',completedCycleIds:[]}));let calls=0;const monitor=createAutonomousPaperMonitor({enabled:true,filePath:state,cycleEvidence:next,runCycle:async()=>{calls++;return {ok:true};},now:()=>Date.parse('2026-09-22T01:00:00.000Z')});const result=await monitor.runOnce();assert.equal(result.status,'COLLECTION_CLOSED');assert.equal(calls,0);assert.equal(next.health().newCandidateAdmissionAllowed,false);});

test('legacy evidence runtime remains uncapped outside protected campaigns',t=>{const r=createCycleEvidenceRuntime({directory:root(t),protocolId:'legacy-protocol-v1',campaignId:'legacy-campaign',historyStore:createHistoryStore()});r.recover();for(let i=0;i<51;i++){const id=`autonomous-paper-monitor-v1:${i}`;r.openMonitorCycle(id);r.sealMonitorCycle(id);}assert.equal(r.health().candidateCycleLimit,null);assert.equal(r.health().collectionClosed,false);});

test('OOS2U draft freezes structure but contains no production identity or activation',()=>{assert.equal(OOS2U_STRUCTURAL_CONTRACT.frozenThreshold,0.599936);assert.equal(OOS2U_STRUCTURAL_CONTRACT.operator,'<=');assert.equal(OOS2U_STRUCTURAL_CONTRACT.candidateCycles,50);assert.equal(OOS2U_STRUCTURAL_CONTRACT.replacement,'NONE');assert.equal(OOS2U_STRUCTURAL_CONTRACT.protectedProspectiveMutationIsolation,true);assert.equal(validateOos2uDraft({...OOS2U_STRUCTURAL_CONTRACT}),true);assert.throws(()=>validateOos2uDraft({...OOS2U_STRUCTURAL_CONTRACT,campaignId:'real'}),/PRODUCTION_IDENTITY/);});
