import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { tmpdir } from 'node:os';
import historyRouter from '../backend/src/routes/history.js';
import { settleDuePaperCampaignOutcomes } from '../backend/src/paperOutcomeSettlement.js';
import { createHistoryStore, createHistoryStoreWithPaperAuthority } from '../learning/src/historyStore.js';
import { createCycleEvidenceRuntime } from '../learning/src/cycleEvidenceRuntime.js';
import { createAutonomousPaperMonitor } from '../learning/src/autonomousPaperMonitor.js';
import { OOS2U_PROTOCOL, OOS2U_STRUCTURAL_CONTRACT, validateOos2uDraft } from '../backend/src/oos2uProtocol.js';

const campaign='fixture-oos2u-campaign', cycleId='autonomous-paper-monitor-v1:1';
const membership={protocolId:OOS2U_PROTOCOL,campaignId:campaign,cycleId,writerGeneration:1};
const root=t=>{const value=fs.mkdtempSync(path.join(tmpdir(),'oos2u-isolation-'));t.after(()=>fs.rmSync(value,{recursive:true,force:true}));return value;};
function protectedBundle(){const bundle=createHistoryStoreWithPaperAuthority({now:()=> '2026-09-22T00:00:10.000Z',id:()=> 'protected-record'}),store=bundle.historyStore;const record=store.prepareDecisionRecord({decision:{direction:'BUY',releaseEligible:true,clickTime:'2026-09-22T00:00:00.000Z'},data:{asset:'EUR/USD',timeframe:'1min',price:1.1},context:{monitorCycleId:cycleId,expirySeconds:60}},membership);store.insertPreparedRecord(record);return bundle;}
function route(method,routePath){return historyRouter.stack.find(layer=>layer.route?.path===routePath&&layer.route.methods[method]).route.stack.at(-1).handle;}
function response(){return {code:200,body:null,status(value){this.code=value;return this;},json(value){this.body=value;return this;}};}

test('public store cannot forge PAPER authority while private port remains valid',()=>{const {historyStore:store,paperMutationPort}=protectedBundle();assert.deepEqual(Object.keys(store).sort(),['confirmExecution','insertPreparedRecord','insertPreparedRecords','list','prepareDecisionRecord','recordDecision','settle'].sort());assert.equal(store.confirmPaperExecution,undefined);assert.equal(store.settlePaperOutcome,undefined);assert.throws(()=>store.confirmExecution('protected-record',{actualClickTime:'2026-09-22T00:00:01.000Z',authority:'paper'}),/PROTECTED_PROSPECTIVE_MUTATION_FORBIDDEN/);for(const forged of [{authority:'paper',paperOnly:true},{authority:Symbol('paper')},{settlementVersion:'paper-outcome-settlement-v2',source:'paper-live-temporal-reference-v1'}])assert.throws(()=>store.settle('protected-record','WIN',forged),/PROTECTED_PROSPECTIVE_MUTATION_FORBIDDEN/);const paper=paperMutationPort.confirmPaperExecution('protected-record',{referenceTimestamp:'2026-09-22T00:00:01.000Z',referencePrice:1.1,source:'fixture'});assert.equal(paper.execution.status,'PAPER_CONFIRMED');const closed=paperMutationPort.settlePaperOutcome('protected-record','WIN',{settlementVersion:'paper-outcome-settlement-v2',source:'paper-live-temporal-reference-v1',paperOnly:true,automatedBrokerExecution:false});assert.equal(closed.outcome,'WIN');assert.equal(closed.execution.status,'PAPER_CONFIRMED');});

test('manual API rejects protected execution/outcome and history projection hides it',async()=>{for(const [routePath,body] of [['/history/:id/executed',{actualClickTime:'2026-09-22T00:00:01.000Z'}],['/history/:id/outcome',{outcome:'WIN'}]]){const store=protectedBundle().historyStore,res=response();await route('post',routePath)({params:{id:'protected-record'},body,app:{locals:{historyStore:store}}},res);assert.equal(res.code,400);assert.equal(res.body.error,'PROTECTED_PROSPECTIVE_MUTATION_FORBIDDEN');assert.equal(store.list()[0].status,'OPEN');}const store=protectedBundle().historyStore,res=response();await route('get','/history')({query:{},app:{locals:{historyStore:store}}},res);assert.equal(res.body.total,0);assert.deepEqual(res.body.records,[]);});

test('generic resolver never selects a protected record',async()=>{const store=protectedBundle().historyStore,res=response();await route('post','/history/resolve')({body:{limit:3},app:{locals:{historyStore:store}}},res);assert.equal(res.code,200);assert.deepEqual(res.body,{ok:true,resolved:[],pending:[]});assert.equal(store.list()[0].status,'OPEN');});

test('official PAPER settlement uses private port for WIN LOSS and TIE with exact provenance',()=>{for(const [expected,exitPrice] of [['WIN',1.2],['LOSS',1.0],['TIE',1.1]]){const {historyStore:store,paperMutationPort}=protectedBundle(),feed={referenceAtOrAfter:(_asset,target)=>Number(target)===Date.parse('2026-09-22T00:00:00.000Z')?{provider:'fixture',price:1.1,timestamp:'2026-09-22T00:00:01.000Z',lagMs:1000,valid:true,status:'OK'}:{provider:'fixture',price:exitPrice,timestamp:'2026-09-22T00:01:02.000Z',lagMs:1000,valid:true,status:'OK'}};const result=settleDuePaperCampaignOutcomes({historyStore:store,paperMutationPort,biquoteForexFeed:feed,scope:{protocolId:OOS2U_PROTOCOL,campaignId:campaign},now:Date.parse('2026-09-22T00:01:10.000Z')});assert.equal(result.settled,1);const record=store.list()[0];assert.equal(record.outcome,expected);assert.equal(record.execution.status,'PAPER_CONFIRMED');assert.equal(record.outcomeMetadata.settlementVersion,'paper-outcome-settlement-v2');assert.equal(record.outcomeMetadata.source,'paper-live-temporal-reference-v1');assert.equal(record.outcomeMetadata.automatedBrokerExecution,false);}});

function runtime(t,directory,store=createHistoryStore()){return createCycleEvidenceRuntime({directory,protocolId:OOS2U_PROTOCOL,campaignId:campaign,historyStore:store,observationTerminalRequired:true,maxCandidateCycles:50,now:()=> '2026-09-22T00:00:00.000Z'});}
function fill(runtime,count,start=0){for(let i=start;i<start+count;i++){const id=`autonomous-paper-monitor-v1:${i}`;runtime.openMonitorCycle(id);runtime.commitObservationTerminal(id,{outcome:i===10?'OPERATIONAL_FAILURE':'SUCCESS',reasonCode:i===10?'CYCLE_ERROR':null});runtime.sealMonitorCycle(id);}}

test('hard stop admits exactly slots 1..50 and operational failure is not replaced',t=>{const r=runtime(t,root(t));r.recover();fill(r,50);assert.deepEqual(r.health(),{ready:true,paused:false,observationTerminalRequired:true,candidateCyclesObserved:50,candidateCycleLimit:50,collectionClosed:true,newCandidateAdmissionAllowed:false});assert.throws(()=>r.openMonitorCycle('autonomous-paper-monitor-v1:50'),/EVIDENCE_CANDIDATE_LIMIT_REACHED/);assert.equal(r.health().paused,false);});

test('restart at 50 stays closed and scheduler performs no observation',async t=>{const directory=root(t),store=createHistoryStore(),first=runtime(t,directory,store);first.recover();fill(first,50);const next=runtime(t,directory,store),state=path.join(root(t),'monitor.json');fs.writeFileSync(state,JSON.stringify({monitorVersion:'autonomous-paper-monitor-v1',completedCycleIds:[]}));let calls=0;const monitor=createAutonomousPaperMonitor({enabled:true,filePath:state,cycleEvidence:next,runCycle:async()=>{calls++;return {ok:true};},now:()=>Date.parse('2026-09-22T01:00:00.000Z')});const result=await monitor.runOnce();assert.equal(result.status,'COLLECTION_CLOSED');assert.equal(calls,0);assert.equal(next.health().newCandidateAdmissionAllowed,false);});

test('pending first-50 PAPER record settles after collectionClosed and restart without opening slot 51',async t=>{let n=0;const directory=root(t),bundle=createHistoryStoreWithPaperAuthority({id:()=>`pending-${++n}`,now:()=> '2026-09-22T00:01:10.000Z'}),store=bundle.historyStore,first=runtime(t,directory,store);first.recover();const id='autonomous-paper-monitor-v1:0';first.openMonitorCycle(id);const writer=first.beginCycleWriter(id);first.stageRecord(writer,{decision:{direction:'BUY',releaseEligible:true,clickTime:'2026-09-22T00:00:00.000Z'},data:{asset:'EUR/USD',timeframe:'1min',price:1.1},context:{monitorCycleId:id,expirySeconds:60}});first.commitStagedRecords(writer);first.endCycleWriter(writer);first.commitObservationTerminal(id,{outcome:'SUCCESS'});first.sealMonitorCycle(id);fill(first,49,1);assert.equal(first.health().candidateCyclesObserved,50);const next=runtime(t,directory,store),state=path.join(root(t),'state.json');fs.writeFileSync(state,JSON.stringify({monitorVersion:'autonomous-paper-monitor-v1',completedCycleIds:[]}));let calls=0;const monitor=createAutonomousPaperMonitor({enabled:true,filePath:state,cycleEvidence:next,runCycle:async()=>{calls++;return {ok:true};},now:()=>Date.parse('2026-09-22T02:00:00.000Z')});assert.equal((await monitor.runOnce()).status,'COLLECTION_CLOSED');assert.equal(calls,0);const feed={referenceAtOrAfter:(_asset,target)=>Number(target)===Date.parse('2026-09-22T00:00:00.000Z')?{provider:'fixture',price:1.1,timestamp:'2026-09-22T00:00:01.000Z',lagMs:1000,valid:true,status:'OK'}:{provider:'fixture',price:1.2,timestamp:'2026-09-22T00:01:02.000Z',lagMs:1000,valid:true,status:'OK'}};const result=settleDuePaperCampaignOutcomes({historyStore:store,paperMutationPort:bundle.paperMutationPort,biquoteForexFeed:feed,scope:{protocolId:OOS2U_PROTOCOL,campaignId:campaign},now:Date.parse('2026-09-22T00:01:10.000Z')});assert.equal(result.settled,1);assert.equal(store.list()[0].status,'CLOSED');assert.equal(next.health().candidateCyclesObserved,50);});

test('legacy evidence runtime remains uncapped outside protected campaigns',t=>{const r=createCycleEvidenceRuntime({directory:root(t),protocolId:'legacy-protocol-v1',campaignId:'legacy-campaign',historyStore:createHistoryStore()});r.recover();for(let i=0;i<51;i++){const id=`autonomous-paper-monitor-v1:${i}`;r.openMonitorCycle(id);r.sealMonitorCycle(id);}assert.equal(r.health().candidateCycleLimit,null);assert.equal(r.health().collectionClosed,false);});

test('OOS2U validator rejects every semantic or production-identity mutation',()=>{assert.equal(validateOos2uDraft({...OOS2U_STRUCTURAL_CONTRACT}),true);const cases=[{bootstrap:{...OOS2U_STRUCTURAL_CONTRACT.bootstrap,replications:1}},{bootstrap:{...OOS2U_STRUCTURAL_CONTRACT.bootstrap,seed:1}},{bootstrap:{...OOS2U_STRUCTURAL_CONTRACT.bootstrap,rng:'other'}},{bootstrap:{...OOS2U_STRUCTURAL_CONTRACT.bootstrap,unit:'record'}},{frozenThreshold:.5},{operator:'>'},{candidateCycles:51},{replacement:'REPLACE'},{activationAuthorized:true}];for(const patch of cases)assert.throws(()=>validateOos2uDraft({...OOS2U_STRUCTURAL_CONTRACT,...patch}),/STRUCTURAL_CONTRACT/);for(const key of ['campaignId','edgeCut','evidenceDirectory'])assert.throws(()=>validateOos2uDraft({...OOS2U_STRUCTURAL_CONTRACT,[key]:'present'}),/PRODUCTION_IDENTITY/);});
