import {clusterBootstrap} from './evaluateOos2.js';import {replayEvidence} from './oos2rEvidence.js';import {sameMembership} from '../../learning/src/cycleEvidenceManifest.js';import {verifyOos2uCycle} from './oos2uEvidence.js';import {isVerifiedOos2uFreeze,isVerifiedOos2uBaselineAudit} from './oos2uFreeze.js';
const official=r=>r.execution?.status==='PAPER_CONFIRMED'&&r.outcomeMetadata?.settlementVersion==='paper-outcome-settlement-v2'&&r.outcomeMetadata?.source==='paper-live-temporal-reference-v1'&&['WIN','LOSS','TIE'].includes(r.outcome);
const performance=rows=>{const WIN=rows.filter(r=>r.outcome==='WIN').length,LOSS=rows.filter(r=>r.outcome==='LOSS').length,TIE=rows.filter(r=>r.outcome==='TIE').length;return {performanceRecords:rows.length,WIN,LOSS,TIE,binaryN:WIN+LOSS,binaryWinRate:WIN+LOSS?WIN/(WIN+LOSS):null};};
export function evaluateOos2u({history=[],walBytes=Buffer.alloc(0),manifests=[],freeze,baselineAudit}={}){
 const r={experiment:'WILL Edge Gate OOS-2U',status:'PRELIMINARY',formalAnalysisAllowed:false,freezeIntegrity:'FAIL',baselineIntegrity:'FAIL',evidenceIntegrity:'FAIL',candidateCyclesObserved:0,candidateCycleLimit:50,collectionClosed:false,newCandidateAdmissionAllowed:false,completedCandidateCycles:0,incompleteCandidateCycles:0,successfulObservationCycles:0,operationalFailureCycles:0,observationFailureReasonCounts:{},noTradeRecords:0,dataInvalidRecords:0,metricValidCycles:0,metricInvalidCycles:0,decisionImpact:'NONE',prospectivePaperAuthorized:false,automatedBrokerExecution:false,ordersExecuted:0,reasonCodes:[]};
 if(!isVerifiedOos2uFreeze(freeze)){r.reasonCodes.push('OOS2U_FREEZE_NOT_AVAILABLE');return r;}r.freezeIntegrity='PASS';if(isVerifiedOos2uBaselineAudit(baselineAudit)&&baselineAudit.baselineCount===freeze.baselineCount&&baselineAudit.baselineIdsSha256===freeze.baselineIdsSha256&&baselineAudit.historyFileSha256===freeze.historyFileSha256)r.baselineIntegrity='PASS';else r.reasonCodes.push('BASELINE_AUDIT_REQUIRED');
 let entries;try{entries=replayEvidence(walBytes,manifests);}catch{r.reasonCodes.push('WAL_UNVERIFIABLE');return r;}if(entries.some(e=>e.manifest.protocolId!==freeze.protocolId||e.manifest.campaignId!==freeze.campaignId)){r.reasonCodes.push('EVIDENCE_IDENTITY_MISMATCH');return r;}const cut=Date.parse(freeze.edgeCut);if(entries.some(e=>!Number.isFinite(Date.parse(e.manifest.openedAt))||Date.parse(e.manifest.openedAt)<=cut)){r.reasonCodes.push('OOS2U_TEMPORAL_MEMBERSHIP_INVALID');return r;}
 const candidates=[...entries].sort((a,b)=>Date.parse(a.manifest.openedAt)-Date.parse(b.manifest.openedAt)||a.manifest.cycleId.localeCompare(b.manifest.cycleId));r.candidateCyclesObserved=candidates.length;r.collectionClosed=candidates.length>=50;r.newCandidateAdmissionAllowed=candidates.length<50;if(candidates.length>50){r.reasonCodes.push('POST_FIRST50_EVIDENCE');return r;}const ambiguity=history.some(x=>(x.protocolId===freeze.protocolId||x.campaignId===freeze.campaignId)&&!candidates.some(e=>sameMembership(x,e.manifest)&&e.manifest.recordIds.includes(x.id)&&x.metadata?.context?.monitorCycleId===e.manifest.cycleId)),checked=candidates.map(entry=>({...verifyOos2uCycle(entry,history),entry}));r.completedCandidateCycles=checked.filter(x=>x.complete).length;r.incompleteCandidateCycles=checked.length-r.completedCandidateCycles;r.successfulObservationCycles=checked.filter(x=>x.observationOutcome==='SUCCESS').length;r.operationalFailureCycles=checked.filter(x=>x.observationOutcome==='OPERATIONAL_FAILURE').length;for(const x of checked.filter(x=>x.observationOutcome==='OPERATIONAL_FAILURE'))r.observationFailureReasonCounts[x.observationFailureReason]=(r.observationFailureReasonCounts[x.observationFailureReason]??0)+1;r.observationFailureReasonCounts=Object.fromEntries(Object.entries(r.observationFailureReasonCounts).sort(([a],[b])=>a.localeCompare(b)));r.noTradeRecords=checked.reduce((n,x)=>n+x.noTradeRecords,0);r.dataInvalidRecords=checked.reduce((n,x)=>n+x.dataInvalidRecords,0);if(ambiguity)r.reasonCodes.push('MEMBERSHIP_AMBIGUITY');if(candidates.length!==50)r.reasonCodes.push('FIRST50_NOT_REACHED');if(checked.some(x=>!x.complete))r.reasonCodes.push('FIRST50_NOT_COMPLETE');r.evidenceIntegrity=!ambiguity&&checked.every(x=>x.valid)?'PASS':'FAIL';
 const evaluated=checked.map(x=>{const rows=x.observationOutcome==='SUCCESS'?x.records.filter(official):[],values=rows.map(y=>y.metadata?.featureSnapshot?.momentum),metricValid=values.length>0&&values.every(Number.isFinite);return {...x,rows,metricValid,mean:metricValid?values.reduce((s,v)=>s+Math.abs(v),0)/values.length:null};});r.metricValidCycles=evaluated.filter(x=>x.metricValid).length;r.metricInvalidCycles=evaluated.length-r.metricValidCycles;if(r.baselineIntegrity!=='PASS'||ambiguity||candidates.length!==50||checked.some(x=>!x.complete))return r;const accepted=evaluated.filter(x=>x.metricValid&&x.mean<=freeze.frozenThreshold),rows=accepted.flatMap(x=>x.rows);r.status='FORMAL_FIRST_50';r.formalAnalysisAllowed=true;r.analysis={metric:freeze.metric,threshold:freeze.frozenThreshold,operator:freeze.operator,acceptedCycles:accepted.length,rejectedCycles:evaluated.filter(x=>x.metricValid&&x.mean>freeze.frozenThreshold).length,invalidMetricCycles:r.metricInvalidCycles,...performance(rows),primaryCI:clusterBootstrap(rows),expectancy:'NOT_AVAILABLE',financialEdge:'NOT_AVAILABLE'};return r;
}
