import fs from 'node:fs';import {fileURLToPath} from 'node:url';
import {baselineCommitment,sha256} from './oos2rEvidence.js';import {canonical} from '../../learning/src/cycleEvidenceManifest.js';import {OOS2U_PROTOCOL,OOS2U_STRUCTURAL_CONTRACT} from './oos2uProtocol.js';
const freezes=new WeakSet(),audits=new WeakSet();const freezeDeep=v=>{if(v&&typeof v==='object'){Object.values(v).forEach(freezeDeep);Object.freeze(v);}return v;};
const exactKeys=(v,keys)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).sort().join('|')===[...keys].sort().join('|');
export const baselineRecordsDigest=records=>sha256(Buffer.from(canonical(records),'utf8'));
export const isVerifiedOos2uFreeze=v=>freezes.has(v);export const isVerifiedOos2uBaselineAudit=v=>audits.has(v);
export function readOos2uFreeze(file,hashFile){
  if(!file||!hashFile)throw Error('OOS2U_FREEZE_PATHS_REQUIRED');const p=file instanceof URL?fileURLToPath(file):file,h=hashFile instanceof URL?fileURLToPath(hashFile):hashFile,expected=fs.readFileSync(h,'utf8').trim().toLowerCase();if(!/^[a-f0-9]{64}$/.test(expected))throw Error('OOS2U_FREEZE_INVALID');const bytes=fs.readFileSync(p);if(sha256(bytes)!==expected)throw Error('OOS2U_FREEZE_INVALID');const v=JSON.parse(bytes.toString('utf8').replace(/^\uFEFF/,'')),c=OOS2U_STRUCTURAL_CONTRACT;
  const top=['schemaVersion','policy','experiment','protocolId','campaignId','edgeCut','createdAt','sourceHead','mode','metric','frozenThreshold','operator','baselineCount','baselineIdsSha256','baselineRecordsSha256','historyFileSha256','checkpoint','bootstrap','protectedProspectiveMutationIsolation','automatedBrokerExecution','noRetuning','noEarlyStopping','noAutomaticLivePromotion','activationAuthorized'];
  if(!exactKeys(v,top)||!exactKeys(v.checkpoint,['candidateCycles','selection','replacement'])||!exactKeys(v.bootstrap,['unit','replications','seed','rng'])||v.schemaVersion!=='edge-gate-oos2u-freeze-v1'||v.policy!=='IMMUTABLE_AFTER_FREEZE'||v.experiment!=='WILL Edge Gate OOS-2U'||v.protocolId!==OOS2U_PROTOCOL||typeof v.campaignId!=='string'||!v.campaignId||!Number.isFinite(Date.parse(v.edgeCut))||!Number.isFinite(Date.parse(v.createdAt))||Date.parse(v.createdAt)<Date.parse(v.edgeCut)||!/^[a-f0-9]{40}$/i.test(v.sourceHead??'')||v.mode!==c.mode||v.metric!==c.metric||v.frozenThreshold!==c.frozenThreshold||v.operator!==c.operator||!Number.isSafeInteger(v.baselineCount)||v.baselineCount<0||!/^[a-f0-9]{64}$/i.test(v.baselineIdsSha256??'')||!/^[a-f0-9]{64}$/i.test(v.baselineRecordsSha256??'')||!/^[a-f0-9]{64}$/i.test(v.historyFileSha256??'')||v.checkpoint?.candidateCycles!==50||v.checkpoint?.selection!=='first 50 exact campaign cycles ordered by openedAt then cycleId'||v.checkpoint?.replacement!=='NONE'||v.bootstrap?.unit!=='cycle'||v.bootstrap?.replications!==10000||v.bootstrap?.seed!==20260915||v.bootstrap?.rng!=='xorshift32'||v.protectedProspectiveMutationIsolation!==true||v.automatedBrokerExecution!==false||v.noRetuning!==true||v.noEarlyStopping!==true||v.noAutomaticLivePromotion!==true||v.activationAuthorized!==false)throw Error('OOS2U_FREEZE_INVALID');
  const result=freezeDeep({...v,freezeSha256:expected});freezes.add(result);return result;
}
export function auditOos2uBaselinePrefix(history,freeze){if(!Array.isArray(history)||!isVerifiedOos2uFreeze(freeze)||history.length<freeze.baselineCount)throw Error('OOS2U_BASELINE_AUDIT_FAILED');const prefix=history.slice(0,freeze.baselineCount),commitment=baselineCommitment(prefix),baselineRecordsSha256=baselineRecordsDigest(prefix);if(commitment.baselineCount!==freeze.baselineCount||commitment.baselineIdsSha256!==freeze.baselineIdsSha256||baselineRecordsSha256!==freeze.baselineRecordsSha256)throw Error('OOS2U_BASELINE_AUDIT_FAILED');const result=freezeDeep({schemaVersion:'oos2u-baseline-audit-v1',status:'PASS',...commitment,baselineRecordsSha256});audits.add(result);return result;}
export function auditOos2uBaselineBytes(bytes,freeze){if(!Buffer.isBuffer(bytes)||!isVerifiedOos2uFreeze(freeze))throw Error('OOS2U_BASELINE_AUDIT_INVALID');const history=JSON.parse(bytes.toString('utf8').replace(/^\uFEFF/,'')),historyFileSha256=sha256(bytes),prefix=auditOos2uBaselinePrefix(history,freeze);if(history.length!==freeze.baselineCount||historyFileSha256!==freeze.historyFileSha256)throw Error('OOS2U_BASELINE_AUDIT_FAILED');const result=freezeDeep({...prefix,historyFileSha256});audits.add(result);return result;}
