import fs from 'node:fs';import path from 'node:path';
import {createCycleEvidenceRuntime} from '../../learning/src/cycleEvidenceRuntime.js';
import {baselineCommitment,replayEvidence} from './oos2rEvidence.js';import {OOS2T_PROTOCOL,verifyOos2tCycle} from './oos2tEvidence.js';
import {readOos2tFreeze,auditOos2tBaselineBytes} from './oos2tFreeze.js';
export const OOS2T_START_AUTHORIZATION='START_APPROVED_OOS2T_FIRST_COLLECTION_V1';
const fail=code=>{throw new Error(code);};
function safeAbsolute(value,code){if(typeof value!=='string'||!path.isAbsolute(value))fail(code);return path.resolve(value);}
function assertHistory(history,bytes,freeze){const audit=auditOos2tBaselineBytes(bytes,freeze),commitment=baselineCommitment(history);if(commitment.baselineCount!==freeze.baselineCount||commitment.baselineIdsSha256!==freeze.baselineIdsSha256)fail('OOS2T_BASELINE_CONTINUITY_FAILED');if(history.some(r=>r?.protocolId===freeze.protocolId||r?.campaignId===freeze.campaignId))fail('OOS2T_EXISTING_MEMBERSHIP');return audit;}
function scan(root,freeze){safeAbsolute(root,'OOS2T_SCAN_ROOT_INVALID');if(!fs.existsSync(root)||fs.lstatSync(root).isSymbolicLink())fail('OOS2T_SCAN_ROOT_INVALID');for(const item of fs.readdirSync(root,{withFileTypes:true})){if(item.isSymbolicLink())fail('OOS2T_SCAN_SYMLINK');const p=path.join(root,item.name);if(item.isDirectory()){scan(p,freeze);continue;}if(!item.name.endsWith('.manifest.json')&&item.name!=='journal.jsonl')continue;let text;try{text=fs.readFileSync(p,'utf8');}catch{fail('OOS2T_SCAN_INVALID');}if(text.includes(freeze.protocolId)||text.includes(freeze.campaignId))fail('OOS2T_EXISTING_EVIDENCE');}}
export function inspectOos2tActivation({historyFile,evidenceDirectory,scanRoots,freezeFile,freezeHashFile,now=()=>Date.now(),readFreeze=readOos2tFreeze}={}){
  const freeze=readFreeze(freezeFile,freezeHashFile),historyPath=safeAbsolute(historyFile,'OOS2T_ABSOLUTE_PATH_REQUIRED'),evidencePath=safeAbsolute(evidenceDirectory,'OOS2T_ABSOLUTE_PATH_REQUIRED');
  if(fs.lstatSync(historyPath).isSymbolicLink())fail('OOS2T_HISTORY_SYMLINK');const historyDirectory=path.dirname(historyPath),relative=path.relative(historyDirectory,evidencePath);if(!relative||relative.startsWith('..')||path.isAbsolute(relative))fail('OOS2T_EVIDENCE_MUST_BE_NEW_HISTORY_CHILD');
  const bytes=fs.readFileSync(historyPath),history=JSON.parse(bytes.toString('utf8').replace(/^\uFEFF/,'')),audit=assertHistory(history,bytes,freeze);if(fs.existsSync(evidencePath))fail('OOS2T_EVIDENCE_DIRECTORY_ALREADY_EXISTS');
  if(!Array.isArray(scanRoots)||!scanRoots.length||!scanRoots.every(path.isAbsolute)||!scanRoots.some(root=>{const r=path.relative(root,historyDirectory);return r===''||(!r.startsWith('..')&&!path.isAbsolute(r));}))fail('OOS2T_SCAN_ROOTS_REQUIRED');for(const root of scanRoots)scan(root,freeze);
  const at=now();if(!Number.isFinite(at)||at<=Date.parse(freeze.edgeCut))fail('OOS2T_NOT_AFTER_EDGE_CUT');return Object.freeze({ready:true,protocolId:freeze.protocolId,campaignId:freeze.campaignId,edgeCut:freeze.edgeCut,freezeIntegrity:'PASS',freezeSha256:freeze.freezeSha256,baselineContinuity:'PASS',baselineCount:audit.baselineCount,baselineIdsSha256:audit.baselineIdsSha256,historyFileSha256:audit.historyFileSha256,existingOos2tCycles:0,started:false,evidenceDirectory:evidencePath});
}
export function prepareOos2tEnvironment(env=process.env,{readFreeze=readOos2tFreeze,now=()=>Date.now()}={}){
  const requested=env.WILL_OOS2T_START_AUTHORIZATION!==undefined||env.WILL_OOS2T_EVIDENCE_SCAN_ROOTS!==undefined||env.WILL_OOS2T_FREEZE_FILE!==undefined||env.WILL_OOS2T_FREEZE_HASH_FILE!==undefined||env.WILL_CYCLE_EVIDENCE_PROTOCOL_ID===OOS2T_PROTOCOL;
  if(!requested)return null;if(env.WILL_OOS2T_START_AUTHORIZATION!==OOS2T_START_AUTHORIZATION||env.WILL_CYCLE_EVIDENCE_ENABLED!=='true'||env.WILL_CYCLE_EVIDENCE_PROTOCOL_ID!==OOS2T_PROTOCOL)fail('OOS2T_EXACT_ACTIVATION_CONFIGURATION_REQUIRED');
  const freeze=readFreeze(env.WILL_OOS2T_FREEZE_FILE,env.WILL_OOS2T_FREEZE_HASH_FILE);if(env.WILL_CYCLE_EVIDENCE_CAMPAIGN_ID!==freeze.campaignId)fail('OOS2T_EXACT_ACTIVATION_CONFIGURATION_REQUIRED');
  const options={historyFile:env.WILL_HISTORY_FILE,evidenceDirectory:env.WILL_CYCLE_EVIDENCE_DIRECTORY,scanRoots:JSON.parse(env.WILL_OOS2T_EVIDENCE_SCAN_ROOTS??'null'),freezeFile:env.WILL_OOS2T_FREEZE_FILE,freezeHashFile:env.WILL_OOS2T_FREEZE_HASH_FILE};
  return Object.freeze({options,freeze,report:inspectOos2tActivation({...options,now,readFreeze:()=>freeze})});
}
export function inspectOos2tRestart({evidenceDirectory,history,freezeFile,freezeHashFile,readFreeze=readOos2tFreeze}={}){
  const freeze=readFreeze(freezeFile,freezeHashFile),directory=safeAbsolute(evidenceDirectory,'OOS2T_RESTART_EVIDENCE_REQUIRED');if(!fs.existsSync(directory)||fs.lstatSync(directory).isSymbolicLink()||fs.existsSync(path.join(directory,'writer.lock')))fail('OOS2T_RESTART_EVIDENCE_INVALID');if(!Array.isArray(history))fail('OOS2T_RESTART_HISTORY_REQUIRED');
  const wal=fs.readFileSync(path.join(directory,'journal.jsonl')),manifests=fs.readdirSync(directory).filter(x=>x.endsWith('.manifest.json')).map(x=>JSON.parse(fs.readFileSync(path.join(directory,x),'utf8'))),entries=replayEvidence(wal,manifests);
  if(entries.some(e=>!e.projectionValid||e.manifest.protocolId!==freeze.protocolId||e.manifest.campaignId!==freeze.campaignId))fail('OOS2T_RESTART_EVIDENCE_INVALID');if(entries.some(e=>!Number.isFinite(Date.parse(e.manifest.openedAt))||Date.parse(e.manifest.openedAt)<=Date.parse(freeze.edgeCut)))fail('OOS2T_TEMPORAL_MEMBERSHIP_INVALID');const generations=entries.map(e=>e.manifest.writerGeneration).sort((a,b)=>a-b);if(generations.some((v,i)=>v!==i+1))fail('OOS2T_RESTART_GENERATION_INVALID');const checks=entries.map(e=>verifyOos2tCycle(e,history)),ambiguity=history.some(r=>(r?.protocolId===freeze.protocolId||r?.campaignId===freeze.campaignId)&&!entries.some(e=>e.manifest.recordIds.includes(r?.id)));if(ambiguity||checks.some(x=>!x.valid||!x.complete))fail('OOS2T_RESTART_NOT_FULLY_SEALED');
  return Object.freeze({recoverable:true,writableRecoveryAuthorized:false,cycles:entries.length,successfulObservationCycles:checks.filter(x=>x.observationOutcome==='SUCCESS').length,observationFailureCycles:checks.filter(x=>x.observationOutcome==='OPERATIONAL_FAILURE').length});
}
export function createPreparedOos2tRuntime({prepared,historyStore,now=()=>Date.now(),readFreeze=readOos2tFreeze}={}){
  if(!prepared?.options||!prepared?.freeze)fail('OOS2T_PREPARED_ENVIRONMENT_REQUIRED');const freeze=readFreeze(prepared.options.freezeFile,prepared.options.freezeHashFile),fresh=inspectOos2tActivation({...prepared.options,now,readFreeze:()=>freeze});
  const bytes=fs.readFileSync(prepared.options.historyFile);assertHistory(historyStore.list(),bytes,freeze);fs.mkdirSync(fresh.evidenceDirectory);let first=true;
  const runtime=createCycleEvidenceRuntime({directory:fresh.evidenceDirectory,protocolId:freeze.protocolId,campaignId:freeze.campaignId,historyStore,observationTerminalRequired:true,maxCandidateCycles:50,now:()=>{const at=now();if(!Number.isFinite(at)||at<=Date.parse(freeze.edgeCut))fail('OOS2T_NOT_AFTER_EDGE_CUT');return new Date(at).toISOString();}}),open=runtime.openMonitorCycle.bind(runtime);
  runtime.openMonitorCycle=cycleId=>{if(first){try{const current=fs.readFileSync(prepared.options.historyFile);assertHistory(historyStore.list(),current,freeze);}catch{runtime.pause();fail('OOS2T_BASELINE_CHANGED_BEFORE_FIRST_OPEN');}}const manifest=open(cycleId);first=false;return manifest;};return runtime;
}
